language: java
env:
  global:
    secure: KZrLr5Z2kqFpTwSKHpGiMHc+VQqM73of/UPiO7PcJGsc4FFI+abgXD5ETpr+yGTH1NHS5V2OxTgtNSEuZSVGq+wsnKpvnOwoj6NaBIuSOypYI2bShcIk8TGvxSs1AqapE+lX4nsbJeNNEEf8J4sDSHVPA63oVzb0O8MhQ8WzzPo2eX6s/fMcwWumHghtYXfWNXpCABNuSg+E5f2BqpRST62Dv7pqCsOdCFHVkq7+FCXIvvIJK7eC0GZM2aOabk1wyrwwtqLANNxIls8Pq5H7kK8+7qYlIqPLYyHLlq9NDJZ7Gov0haebFeFeYrZHVuNOkyhH2mwY19lTkmaLCImIpRCGk7IEfTZ8FDkgZlkbAS79vux05ctPn66FSqd1zc6XPfMi6bjdcGoDXFujhBHTPoYPXHBfaMDYbpvKg6MpxHpwHDRKe9vfsucYrE7mYvk9Du32TfnSgoiXAC48qLKo57wjKXn07VmFt2BsViDixWMsjVXwKdmGSMSBzJJNFdl7y4sYkgYi9Zul9D/IUdIeSR6bKGxik0qfTaj4ty1YNW0p1S6zL4WUBuGhPPnzXBelQuHzKXKe4OMBf4sLs3xSF1078XwunE5paXPl/qey5QXQhFP3XIWXENYDKK6MeeqMZiu24qZ2tIl7waMIDZObLy5U+57UE1ZH5v4B3mbqlnI=

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "visiativ"
    token:
      secure: "aql++X2M9LhAX7W5mpk9W2H6XfhDwFbgy+edBwWAI8Ky3IUedWDWoEqzSt3qcWzFpBc44SOrewzMkLQB5sd23Liliiwg2/aS3xhcIAyF8kwBRNaqhWaMzmFpy+JCO1hBXg+iMUUFdzG6lnLFZbOmLozqFQeOhdHKLb9X73gyo0FYaOxPbB4dG00kgF18xOwtkls+OGBJNw2yxbYfSuH0ND31YTWhB/6PQ8VPTuKIOU7tKbHkI9h/JDz8wrdDIR1hYTj8KuUfUQ5/HRZ6BN8Jp2Jq2dphCvMgRK+hFz//CwlLqw5huAoVov49gNFUm4rOm/P5DUiRB1iBgw5XZBR5MyhIyTJsFoxaKo+1KDDSLyBno6d0gPca71hPeM4nArFfrKP7lFgZVC61oq2Dj670oJFQ6plFsrpHxe3jdd/H40x4iq5sn70zn6bih5LTyy/3EeQ0xcisqeBG1twMve1tp4Tjoh+NhnVLbBZLdiTZr8eIzP19VcbV99oR5YCrtu9m5cVa3VAICF3L4P9g7ST3oXKTM3X3vtkKTEFwIgf2v3D6Bqv4e4PYhsYbB/ajiUbVP7SJcnsOwoZtoETilvZOsgzoEhfhkTLNmJIuLb9tzux83pNp3oqubyrdHBocFU1MDzt3xVpPirbuyzY1u715pChGA85G6DJ99QDmQUaBfZI="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
